# Application name
spring.application.name=netflix-api

# Server configuration
server.port=8080

# Logging level
logging.level.org.springframework.web=INFO

# Jackson (JSON) configuration
spring.jackson.serialization.indent_output=true

# Error handling
server.error.include-message=always
server.error.include-binding-errors=always